version: "3"
services:
  pg-bkup:
    image: jkaninda/pg-bkup
    container_name: pg-bkup
    command:
      - /bin/sh
      - -c
      - bkup --operation backup --dbname database_name
    volumes:
      - ./backup:/backup
    environment:
      - DB_PORT=5432
      - DB_HOST=postgress
      - DB_USERNAME=userName
      - DB_PASSWORD=${DB_PASSWORD}