version: "3"
services:
  pg-bkup:
    image: jkaninda/pg-bkup
    container_name: pg-bkup
    command: backup --dbname database_name #--cron-expression "@every 5m"
    volumes:
      - ./backup:/backup
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_USERNAME=userName
      - DB_PASSWORD=${DB_PASSWORD}
      # Check https://jkaninda.github.io/pg-bkup/reference/#predefined-schedules
      - BACKUP_CRON_EXPRESSION=@daily #@every 5m|@weekly | @monthly |0 1 * * *

