apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
        - name: pg-bkup
          # In production, it is advised to lock your image tag to a proper
          # release version instead of using `latest`.
          # Check https://github.com/jkaninda/pg-bkup/releases
          # for a list of available releases.
          image: jkaninda/pg-bkup
          command:
            - /bin/sh
            - -c
            - bkup
            - backup
            - --storage
            - s3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: ""
            - name: DB_NAME
              value: ""
            - name: DB_USERNAME
              value: ""
            # Please use secret!
            - name: DB_PASSWORD
              value: ""
            - name: AWS_S3_ENDPOINT
              value: "https://s3.amazonaws.com"
            - name: AWS_S3_BUCKET_NAME
              value: "xxx"
            - name: AWS_REGION
              value: "us-west-2"
            - name: AWS_ACCESS_KEY
              value: "xxxx"
            - name: AWS_SECRET_KEY
              value: "xxxx"
            - name: AWS_DISABLE_SSL
              value: "false"