name: Build
on:
  push:
    branches: [ "main"]
  workflow_dispatch:
      inputs:
        docker_tag:
          description: 'Docker tag'
          required: true
          default: 'latest' 
          type: string
env:
  BUILDKIT_IMAGE: jkaninda/pg-bkup
  TAG: v1.0
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: "./docker/Dockerfile"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
           "${{env.BUILDKIT_IMAGE}}:${{env.TAG}}"
        #   "${{env.BUILDKIT_IMAGE}}:latest"
           "ghcr.io/${{env.BUILDKIT_IMAGE}}:${{TAG}}"
       #    "ghcr.io/${{env.BUILDKIT_IMAGE}}:latest"
